//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.UserEndPoint {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoints.realestate.com.et/", ConfigurationName="UserEndPoint.UserEndPoint")]
    public interface UserEndPoint {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.authResponse auth(RealEstate.UserEndPoint.auth request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.authResponse> authAsync(RealEstate.UserEndPoint.auth request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.activateUserResponse activateUser(RealEstate.UserEndPoint.activateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.activateUserResponse> activateUserAsync(RealEstate.UserEndPoint.activateUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.findByIdResponse findById(RealEstate.UserEndPoint.findById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.findByIdResponse> findByIdAsync(RealEstate.UserEndPoint.findById request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.deactivateUserResponse deactivateUser(RealEstate.UserEndPoint.deactivateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.deactivateUserResponse> deactivateUserAsync(RealEstate.UserEndPoint.deactivateUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.listUserResponse listUser(RealEstate.UserEndPoint.listUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.listUserResponse> listUserAsync(RealEstate.UserEndPoint.listUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.changePasswordUserResponse changePasswordUser(RealEstate.UserEndPoint.changePasswordUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.changePasswordUserResponse> changePasswordUserAsync(RealEstate.UserEndPoint.changePasswordUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.updateUserResponse updateUser(RealEstate.UserEndPoint.updateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.updateUserResponse> updateUserAsync(RealEstate.UserEndPoint.updateUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.deleteUserResponse deleteUser(RealEstate.UserEndPoint.deleteUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.deleteUserResponse> deleteUserAsync(RealEstate.UserEndPoint.deleteUser request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.meResponse me(RealEstate.UserEndPoint.me request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.meResponse> meAsync(RealEstate.UserEndPoint.me request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RealEstate.UserEndPoint.createUserResponse createUser(RealEstate.UserEndPoint.createUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.createUserResponse> createUserAsync(RealEstate.UserEndPoint.createUser request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class authDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class userListResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private paginationDto paginationDtoField;
        
        private responseDto responseDtoField;
        
        private userDto[] userDtoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public paginationDto paginationDto {
            get {
                return this.paginationDtoField;
            }
            set {
                this.paginationDtoField = value;
                this.RaisePropertyChanged("paginationDto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public responseDto responseDto {
            get {
                return this.responseDtoField;
            }
            set {
                this.responseDtoField = value;
                this.RaisePropertyChanged("responseDto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userDtoList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public userDto[] userDtoList {
            get {
                return this.userDtoListField;
            }
            set {
                this.userDtoListField = value;
                this.RaisePropertyChanged("userDtoList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class paginationDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private int maxField;
        
        private bool maxFieldSpecified;
        
        private int startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpecified {
            get {
                return this.maxFieldSpecified;
            }
            set {
                this.maxFieldSpecified = value;
                this.RaisePropertyChanged("maxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class responseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class userDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string companyField;
        
        private System.DateTime createdatField;
        
        private bool createdatFieldSpecified;
        
        private string emailField;
        
        private string fnameField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string lnameField;
        
        private string passwordField;
        
        private string phoneField;
        
        private bool statusField;
        
        private string typeField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime createdat {
            get {
                return this.createdatField;
            }
            set {
                this.createdatField = value;
                this.RaisePropertyChanged("createdat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdatSpecified {
            get {
                return this.createdatFieldSpecified;
            }
            set {
                this.createdatFieldSpecified = value;
                this.RaisePropertyChanged("createdatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
                this.RaisePropertyChanged("fname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
                this.RaisePropertyChanged("lname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://endpoints.realestate.com.et/")]
    public partial class authResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private bool statusField;
        
        private string tokenField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class auth {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.authDto AuthDto;
        
        public auth() {
        }
        
        public auth(RealEstate.UserEndPoint.authDto AuthDto) {
            this.AuthDto = AuthDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class authResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.authResponseDto @return;
        
        public authResponse() {
        }
        
        public authResponse(RealEstate.UserEndPoint.authResponseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class activateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public activateUser() {
        }
        
        public activateUser(long userId, string token) {
            this.userId = userId;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activateUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class activateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public activateUserResponse() {
        }
        
        public activateUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findById", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class findById {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public findById() {
        }
        
        public findById(long userId, string token) {
            this.userId = userId;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByIdResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class findByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.userDto @return;
        
        public findByIdResponse() {
        }
        
        public findByIdResponse(RealEstate.UserEndPoint.userDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deactivateUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class deactivateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public deactivateUser() {
        }
        
        public deactivateUser(long userId, string token) {
            this.userId = userId;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deactivateUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class deactivateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public deactivateUserResponse() {
        }
        
        public deactivateUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class listUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.paginationDto paginationDto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public listUser() {
        }
        
        public listUser(RealEstate.UserEndPoint.paginationDto paginationDto, string token) {
            this.paginationDto = paginationDto;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class listUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.userListResponseDto @return;
        
        public listUserResponse() {
        }
        
        public listUserResponse(RealEstate.UserEndPoint.userListResponseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class changePasswordUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public changePasswordUser() {
        }
        
        public changePasswordUser(string newPassword, string token) {
            this.newPassword = newPassword;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class changePasswordUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public changePasswordUserResponse() {
        }
        
        public changePasswordUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class updateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.userDto userDto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public updateUser() {
        }
        
        public updateUser(RealEstate.UserEndPoint.userDto userDto, string token) {
            this.userDto = userDto;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class updateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public updateUserResponse() {
        }
        
        public updateUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class deleteUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public deleteUser() {
        }
        
        public deleteUser(long userId, string token) {
            this.userId = userId;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class deleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public deleteUserResponse() {
        }
        
        public deleteUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="me", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class me {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public me() {
        }
        
        public me(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="meResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class meResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.userDto @return;
        
        public meResponse() {
        }
        
        public meResponse(RealEstate.UserEndPoint.userDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class createUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.userDto userDto;
        
        public createUser() {
        }
        
        public createUser(RealEstate.UserEndPoint.userDto userDto) {
            this.userDto = userDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://endpoints.realestate.com.et/", IsWrapped=true)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoints.realestate.com.et/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealEstate.UserEndPoint.responseDto @return;
        
        public createUserResponse() {
        }
        
        public createUserResponse(RealEstate.UserEndPoint.responseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserEndPointChannel : RealEstate.UserEndPoint.UserEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserEndPointClient : System.ServiceModel.ClientBase<RealEstate.UserEndPoint.UserEndPoint>, RealEstate.UserEndPoint.UserEndPoint {
        
        public UserEndPointClient() {
        }
        
        public UserEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.authResponse RealEstate.UserEndPoint.UserEndPoint.auth(RealEstate.UserEndPoint.auth request) {
            return base.Channel.auth(request);
        }
        
        public RealEstate.UserEndPoint.authResponseDto auth(RealEstate.UserEndPoint.authDto AuthDto) {
            RealEstate.UserEndPoint.auth inValue = new RealEstate.UserEndPoint.auth();
            inValue.AuthDto = AuthDto;
            RealEstate.UserEndPoint.authResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).auth(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.authResponse> RealEstate.UserEndPoint.UserEndPoint.authAsync(RealEstate.UserEndPoint.auth request) {
            return base.Channel.authAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.authResponse> authAsync(RealEstate.UserEndPoint.authDto AuthDto) {
            RealEstate.UserEndPoint.auth inValue = new RealEstate.UserEndPoint.auth();
            inValue.AuthDto = AuthDto;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).authAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.activateUserResponse RealEstate.UserEndPoint.UserEndPoint.activateUser(RealEstate.UserEndPoint.activateUser request) {
            return base.Channel.activateUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto activateUser(long userId, string token) {
            RealEstate.UserEndPoint.activateUser inValue = new RealEstate.UserEndPoint.activateUser();
            inValue.userId = userId;
            inValue.token = token;
            RealEstate.UserEndPoint.activateUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).activateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.activateUserResponse> RealEstate.UserEndPoint.UserEndPoint.activateUserAsync(RealEstate.UserEndPoint.activateUser request) {
            return base.Channel.activateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.activateUserResponse> activateUserAsync(long userId, string token) {
            RealEstate.UserEndPoint.activateUser inValue = new RealEstate.UserEndPoint.activateUser();
            inValue.userId = userId;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).activateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.findByIdResponse RealEstate.UserEndPoint.UserEndPoint.findById(RealEstate.UserEndPoint.findById request) {
            return base.Channel.findById(request);
        }
        
        public RealEstate.UserEndPoint.userDto findById(long userId, string token) {
            RealEstate.UserEndPoint.findById inValue = new RealEstate.UserEndPoint.findById();
            inValue.userId = userId;
            inValue.token = token;
            RealEstate.UserEndPoint.findByIdResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).findById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.findByIdResponse> RealEstate.UserEndPoint.UserEndPoint.findByIdAsync(RealEstate.UserEndPoint.findById request) {
            return base.Channel.findByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.findByIdResponse> findByIdAsync(long userId, string token) {
            RealEstate.UserEndPoint.findById inValue = new RealEstate.UserEndPoint.findById();
            inValue.userId = userId;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).findByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.deactivateUserResponse RealEstate.UserEndPoint.UserEndPoint.deactivateUser(RealEstate.UserEndPoint.deactivateUser request) {
            return base.Channel.deactivateUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto deactivateUser(long userId, string token) {
            RealEstate.UserEndPoint.deactivateUser inValue = new RealEstate.UserEndPoint.deactivateUser();
            inValue.userId = userId;
            inValue.token = token;
            RealEstate.UserEndPoint.deactivateUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).deactivateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.deactivateUserResponse> RealEstate.UserEndPoint.UserEndPoint.deactivateUserAsync(RealEstate.UserEndPoint.deactivateUser request) {
            return base.Channel.deactivateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.deactivateUserResponse> deactivateUserAsync(long userId, string token) {
            RealEstate.UserEndPoint.deactivateUser inValue = new RealEstate.UserEndPoint.deactivateUser();
            inValue.userId = userId;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).deactivateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.listUserResponse RealEstate.UserEndPoint.UserEndPoint.listUser(RealEstate.UserEndPoint.listUser request) {
            return base.Channel.listUser(request);
        }
        
        public RealEstate.UserEndPoint.userListResponseDto listUser(RealEstate.UserEndPoint.paginationDto paginationDto, string token) {
            RealEstate.UserEndPoint.listUser inValue = new RealEstate.UserEndPoint.listUser();
            inValue.paginationDto = paginationDto;
            inValue.token = token;
            RealEstate.UserEndPoint.listUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).listUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.listUserResponse> RealEstate.UserEndPoint.UserEndPoint.listUserAsync(RealEstate.UserEndPoint.listUser request) {
            return base.Channel.listUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.listUserResponse> listUserAsync(RealEstate.UserEndPoint.paginationDto paginationDto, string token) {
            RealEstate.UserEndPoint.listUser inValue = new RealEstate.UserEndPoint.listUser();
            inValue.paginationDto = paginationDto;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).listUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.changePasswordUserResponse RealEstate.UserEndPoint.UserEndPoint.changePasswordUser(RealEstate.UserEndPoint.changePasswordUser request) {
            return base.Channel.changePasswordUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto changePasswordUser(string newPassword, string token) {
            RealEstate.UserEndPoint.changePasswordUser inValue = new RealEstate.UserEndPoint.changePasswordUser();
            inValue.newPassword = newPassword;
            inValue.token = token;
            RealEstate.UserEndPoint.changePasswordUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).changePasswordUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.changePasswordUserResponse> RealEstate.UserEndPoint.UserEndPoint.changePasswordUserAsync(RealEstate.UserEndPoint.changePasswordUser request) {
            return base.Channel.changePasswordUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.changePasswordUserResponse> changePasswordUserAsync(string newPassword, string token) {
            RealEstate.UserEndPoint.changePasswordUser inValue = new RealEstate.UserEndPoint.changePasswordUser();
            inValue.newPassword = newPassword;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).changePasswordUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.updateUserResponse RealEstate.UserEndPoint.UserEndPoint.updateUser(RealEstate.UserEndPoint.updateUser request) {
            return base.Channel.updateUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto updateUser(RealEstate.UserEndPoint.userDto userDto, string token) {
            RealEstate.UserEndPoint.updateUser inValue = new RealEstate.UserEndPoint.updateUser();
            inValue.userDto = userDto;
            inValue.token = token;
            RealEstate.UserEndPoint.updateUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).updateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.updateUserResponse> RealEstate.UserEndPoint.UserEndPoint.updateUserAsync(RealEstate.UserEndPoint.updateUser request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.updateUserResponse> updateUserAsync(RealEstate.UserEndPoint.userDto userDto, string token) {
            RealEstate.UserEndPoint.updateUser inValue = new RealEstate.UserEndPoint.updateUser();
            inValue.userDto = userDto;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).updateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.deleteUserResponse RealEstate.UserEndPoint.UserEndPoint.deleteUser(RealEstate.UserEndPoint.deleteUser request) {
            return base.Channel.deleteUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto deleteUser(long userId, string token) {
            RealEstate.UserEndPoint.deleteUser inValue = new RealEstate.UserEndPoint.deleteUser();
            inValue.userId = userId;
            inValue.token = token;
            RealEstate.UserEndPoint.deleteUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).deleteUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.deleteUserResponse> RealEstate.UserEndPoint.UserEndPoint.deleteUserAsync(RealEstate.UserEndPoint.deleteUser request) {
            return base.Channel.deleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.deleteUserResponse> deleteUserAsync(long userId, string token) {
            RealEstate.UserEndPoint.deleteUser inValue = new RealEstate.UserEndPoint.deleteUser();
            inValue.userId = userId;
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).deleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.meResponse RealEstate.UserEndPoint.UserEndPoint.me(RealEstate.UserEndPoint.me request) {
            return base.Channel.me(request);
        }
        
        public RealEstate.UserEndPoint.userDto me(string token) {
            RealEstate.UserEndPoint.me inValue = new RealEstate.UserEndPoint.me();
            inValue.token = token;
            RealEstate.UserEndPoint.meResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).me(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.meResponse> RealEstate.UserEndPoint.UserEndPoint.meAsync(RealEstate.UserEndPoint.me request) {
            return base.Channel.meAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.meResponse> meAsync(string token) {
            RealEstate.UserEndPoint.me inValue = new RealEstate.UserEndPoint.me();
            inValue.token = token;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).meAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RealEstate.UserEndPoint.createUserResponse RealEstate.UserEndPoint.UserEndPoint.createUser(RealEstate.UserEndPoint.createUser request) {
            return base.Channel.createUser(request);
        }
        
        public RealEstate.UserEndPoint.responseDto createUser(RealEstate.UserEndPoint.userDto userDto) {
            RealEstate.UserEndPoint.createUser inValue = new RealEstate.UserEndPoint.createUser();
            inValue.userDto = userDto;
            RealEstate.UserEndPoint.createUserResponse retVal = ((RealEstate.UserEndPoint.UserEndPoint)(this)).createUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RealEstate.UserEndPoint.createUserResponse> RealEstate.UserEndPoint.UserEndPoint.createUserAsync(RealEstate.UserEndPoint.createUser request) {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RealEstate.UserEndPoint.createUserResponse> createUserAsync(RealEstate.UserEndPoint.userDto userDto) {
            RealEstate.UserEndPoint.createUser inValue = new RealEstate.UserEndPoint.createUser();
            inValue.userDto = userDto;
            return ((RealEstate.UserEndPoint.UserEndPoint)(this)).createUserAsync(inValue);
        }
    }
}
